#!/bin/bash -l
#SBATCH -D /group/jrigrp10/aphillip/oryza
#SBATCH -J liftover
#SBATCH -o /group/jrigrp10/aphillip/oryza/liftover.out-%j.txt
#SBATCH -e /group/jrigrp10/aphillip/oryza/liftover.error-%j.txt
#SBATCH -t 7-00:00:00
#SBATCH --mem=32G

module load bio
module load minimap2

# Assign file names
glum="data/genome/GCA_000576495.1_Oryza_glumaepatula_v1.5_genomic.fna"
sativa="data/genome/GCA_000004655.2_ASM465v1_genomic.fna"
out="glum_sativa_asm20.sam"

# Align genomes. Use minimap2 to generate sam file. Convert to bam.
#minimap2 -ax asm5 --eqx -t 16 $glum $sativa -o $out
samtools view --threads 16 -b -o ${out%.*}.bam $out

#Convert to PSL format
bamToPsl -dots=100 ${out%.*}.bam ${out%.*}.psl

# Prepare reference genomes
#faToTwoBit data/genome/GCA_000576495.1_Oryza_glumaepatula_v1.5_genomic.fna data/genome/GCA_000576495.1_Oryza_glumaepatula_v1.5_genomic.2bit
#faToTwoBit data/genome/GCA_000004655.2_ASM465v1_genomic.fna data/genome/GCA_000004655.2_ASM465v1_genomic.2bit

# Translate psl files to chains
axtChain -linearGap=medium -psl ${out%.*}.psl \
data/genome/GCA_000576495.1_Oryza_glumaepatula_v1.5_genomic.2bit \
data/genome/GCA_000004655.2_ASM465v1_genomic.2bit \
${out%.*}.chain

# Sort chain
chainSort ${out%.*}.chain ${out%.*}.sorted.chain


# Collect info about chromosome sizes for netting
#twoBitInfo data/genome/GCA_000576495.1_Oryza_glumaepatula_v1.5_genomic.2bit data/genome/rm_genomes/glum.chromInfo
#twoBitInfo data/genome/GCA_000004655.2_ASM465v1_genomic.2bit data/genome/rm_genomes/indica.chromInfo


# Netting: identify alignable regions from chains
chainNet ${out%.*}.sorted.chain \
data/genome/rm_genomes/glum.chromInfo data/genome/rm_genomes/indica.chromInfo \
${out%.*}.net /dev/null


# Select the right alignable regions using the nets to create the 'liftOver' file
netChainSubset ${out%.*}.net  ${out%.*}.sorted.chain  ${out%.*}.liftOver.chain

# LiftOver!
#~/toolsfordayz/liftOver -errorHelp -multiple -minMatch=0.1 \
#data/processed/filtered_snps_bpres/domesticated/oryza_sativa.half.bed \
#${out%.*}.liftOver.chain \
#${out%.*}.lifted.bed \
#${out%.*}.unlifted.bed
